// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgyovqmfmmvizguffubb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBneW92cW1mbW12aXpndWZmdWJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUxMzY3NTgsImV4cCI6MjA1MDcxMjc1OH0.4_vrWGSA7kXfnjxeXovm1QUQdQ92GkhgkBSg7tqrQ_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);